---
title: "Chess API"
author: "LonghaoChen"
date: "3/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(httr)
library(jsonlite)
library(tidyverse)
library(reshape2)
library(curl)
library(dplyr)
```

```{r}
library(readr)
df <- read_csv("data/lichess-01-2014.csv",
  col_types = cols(X1 = col_skip())
)
```
```{r}
# barplot for game mode

ggplot(df, aes(reorder(Mode, Mode, function(x) -length(x)))) + geom_bar()
```

```{r}
ggplot(df, aes(reorder(Result, Result, function(x) -length(x)))) + geom_bar()
```
```{r}
ggplot(df, aes(reorder(`Termination Type`, `Termination Type`, function(x) -length(x)))) + geom_bar()

table(df$`Termination Type`)
```


```{r}
ggplot(df, aes(df$`Average Rating`)) + geom_area(stat = "bin")
```
```{r}
ggplot(df, aes(df$`Rating Difference`)) + geom_area(stat = "bin", binwidth = 10)
```

```{r}
df$moves <- str_count(df$PGN, fixed("."))
```


```{r}
ggplot(df, aes(df$`moves`)) + geom_histogram( aes(y=..density..),# Histogram with density instead of count on y-axis
  binwidth = 1,
  colour = "black", fill = "white") + 
  geom_density(alpha = .2, fill = "#FF6666")
```

```{r}
ggplot() + 
  geom_density(aes(df[df$`Termination Type`=="Normal",]$moves), color = "blue") + 
  geom_density(aes(df[df$`Termination Type`=="Time forfeit",]$moves), color = "red")
```

```{r}
ggplot() + 
  geom_density(aes(df[df$`Mode`=="Bullet",]$moves), color = "blue") + 
  geom_density(aes(df[df$`Mode`=="Blitz",]$moves), color = "red") +
  geom_density(aes(df[df$`Mode`=="Classical",]$moves), color = "black") +
  geom_density(aes(df[df$`Mode`=="Correspondence",]$moves), color = "green")
```

```{r}
ggplot() + 
  geom_density(aes(df[df$`Average Rating`> 750 &df$`Average Rating`<1250,]$moves), color = "blue") + 
  geom_density(aes(df[df$`Average Rating`<1750 & df$`Average Rating`>=1250,]$moves), color = "red") +
  geom_density(aes(df[df$`Average Rating`<2250& df$`Average Rating`>=1750,]$moves), color = "black") +
  geom_density(aes(df[df$`Average Rating`>=2250,]$moves), color = "green")
```

```{r}
mean(df[df$`Average Rating`>=2250,]$moves,na.rm = TRUE)

mean(df[df$`Average Rating`<2250& df$`Average Rating`>=1750,]$moves,na.rm = TRUE)

mean(df[df$`Average Rating`<1750 & df$`Average Rating`>=1250,]$moves,na.rm = TRUE)

mean(df[df$`Average Rating`<=1250,]$moves,na.rm = TRUE)
```
```{r}
df$knight_moves <- str_count(df$PGN, fixed("N"))
df$queen_moves <- str_count(df$PGN, fixed("Q"))
df$king_moves <- str_count(df$PGN, fixed("K"))
df$bishop_moves <- str_count(df$PGN, fixed("B"))
df$rook_moves <- str_count(df$PGN, fixed("R"))
df$short_castle_moves <- str_count(df$PGN, fixed("O-O "))
df$long_castle_moves <- str_count(df$PGN, fixed("O-O-O "))
#assign back to short castle for data cleaning
df$short_castle_moves <- df$short_castle_moves-df$long_castle_moves
```

We have a question. How often, likely, when, and which does the pawn promoted to the last row?
```{r}
df$pawn_promote <- str_count(df$PGN, fixed("="))
ggplot() +
  geom_histogram(aes(df$pawn_promote))

```
```{r}
ggplot() +
  geom_jitter(aes(x=df$moves,y=df$pawn_promote))
```

Calculate the average total moves for each total promotion
```{r}
df %>% group_by(pawn_promote) %>% summarise( average_total_move = mean(moves))
```

```{r}
df$index_equal <- str_locate(df$PGN, "=")
df$before_equal <- substr(df$PGN,0,df$index_equal +1 )

df$last_dot <- lapply(gregexpr("\\.", df$before_equal), tail, 1)

df$last_space <- lapply(gregexpr("\\ ", substr(df$PGN,0,df$last_dot)), tail, 1)

df$move_promote <- as.integer(substr(df$PGN,  as.integer(df$last_space)+1,as.integer(df$last_dot)-1))


```

```{r}
ggplot() + 
  geom_histogram(aes(df[!is.na(df$move_promote), ]$move_promote),stat="count",na.rm = TRUE,binwidth = 1)


sum <- df %>%
  group_by(move_promote) %>%
  summarise(count = n())

sum$move_promote <- as.integer(sum$move_promote)

```
```{r}
df$last_move <- df$moves*3-str_count(df$PGN, fixed(" "))
```

```{r}
df$pawn_moves <- df$moves*2-df$knight_moves-df$queen_moves-df$king_moves-df$bishop_moves-df$rook_moves-df$short_castle_moves-df$long_castle_moves-(df$last_move-1)
```

```{r}
#Add a index column
df$id <- seq.int(nrow(df))

df_long <- melt(df,
        # ID variables - all the variables to keep but not split apart on
    id.vars=c("id", "Mode","Average Rating", "Termination Type"),
        # The source columns
    measure.vars=c("knight_moves", "queen_moves", "king_moves", "bishop_moves", "rook_moves", "short_castle_moves", "long_castle_moves", "pawn_moves" ),
        # Name of the destination column that will identify the original
        # column that the measurement came from
    variable.name="pieces",
    value.name="moves"
)
```


```{r}
f <- ggplot(df_long, aes(x = pieces, y = moves)) 

f + geom_boxplot(scale = "count") + stat_summary(fun.y=mean, geom="point", shape=23, size=2)
```

